version: "3.9"
    
services:
  postgres_db:
    container_name: postgres_db
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: news-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
        
  news.webapi:
    container_name: news.webapi
    image: news.webapi
    build:
      context: .
      dockerfile: News.WebAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DbConnection=Server=postgres_db;Port=5432;Database=news-db;Username=user;Password=123;Pooling=true;
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
    
volumes:
  postgres_data: